### ISSUE TITLE
Consider a classic ETL workflow

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#107]
Currently the code is structured as fetch, decode, transform, dump. I'm proposing we model the workflow to match the established [ETL pattern](https://en.wikipedia.org/wiki/Extract,_transform,_load). "Component" here refers to the abstraction described in #106:

* Extract: Fetch + decode the dependent config files for each component into usable data structures. Cache and reuse files that are shared between components (perhaps a `FileRetriever` type that checks for a cached copy, if miss, download).
* Validate: Ensure the data we've extracted looks correct to prevent garbage-in-garbage-out. This is important and not currently part of the workflow. @dymurray and I have already run into issues due to the lack of validate.
* Transform: Take the old data structures and turn them into the new structures
* Load (Dump, or Flush): Serialize the transformed structures into whatever destination it is that we desire, in this case, a set of CR files.

These methods should be defined on each component we write. A runner should accept a list of these components and execute each of them in sequence (could be parallelized via channels, but let's not pre-optimize).

**Comment by gildub** [comment]
This is why I came up with the pipeline because it's a way of handling workflow like the ETL pattern.
From the beginning we have been working with a Fetch, Decode, Transform, and Dump approach in mind. I suppose it doesn't matter how many steps or operations there are. As long as we pass components along the chain.

The Validation operation is not in the pipe yet but will be. This has been on the back burner because besides validating YAML we need to find out how we can do more.

Yes we want to interface the components for the same operations, those being more FDTD than ETL but that's not an anti-pattern.

Now with more experience on the project we're more keen to deal with interfaces of interfaces.

**Comment by eriknelson** [comment]
@gildub can you explain what you specifically mean by pipeline? The amount of steps definitely don't matter, but we think about the problem from a higher level, we know generally for all the relevant features in OCP4 we have to extract the old files, make sure they're okay, transform them to new ones, and write them out to files. We should strive to recognize the similarities with existing solved problems and leverage their solutions. In this case an ETL pattern is a well established approach for exactly what we're doing.

Re: the interfaces, we shouldn't use interfaces for the sake of it. It's useful because it let's you program to an interface of behavior, which means we can abstract this ETL concept, fill in the details for each component, and hand them all to a runner to execute in a uniform way.

The development model I want to get to is "oh I have a new feature I need to translate. Let me fill in X methods so I'm compliant with the transform interface, and then I can simply hand it to the runner and it will do that work".

On top of that, they make code more testable, but I really think at this point we need to be making some progress on the actual problem at hand rather than mocks.

**Comment by gildub** [comment]
By pipeline I mean a transform chain and we agree that it doesn't matter the number of operations involved. All I was trying to say is yes this is ETL pattern although we didn't express it that way.

I using interface to help handle the operations. It's true that at the beginning it was a challenge to handle the interface in the face of the sub types (OCP3 and OCP4 structures that are interfaces as well (search for kind).

I was initially asked to be more practical and not to worry about the rest and working on the tests (mocking or not).

Meanwhile I raised the design question to be able to correctly handle the requirements. And came up with using go routines as a pipeline (https://github.com/fusor/cpma/pull/64/files). Maybe it's overkill but it solved (and still does) the issue from day 1 and can be compliant with ETL (using OCP4 types transient components especially to solve 1 component/N configs need).

So let's continue together burn cycles to resolve the issue.

**Comment by eriknelson** [comment]
@gildub can you elaborate on what a "transform chain" is? An array of transforms that each have specific methods called on them?

I strongly feel we should not introduce go channels until we hit a specific performance limitation that is an actual problem for users. Again, we should not be seeking perfect code at the expense of any working code at all.

**Comment by gildub** [comment]
@eriknelson ,

What about we discuss the pipeline model offline?

I'm happy to have and respect the ETL pattern for the workflow. 
I'm on a patch making the OCP4 components operable as you mentioned.

**Comment by jmontleon** [comment]
If possible can we keep the conversation in one place so everyone can follow and comment until we get to some sort of resolution? I'd like to understand better the transform pipeline/chain you are proposing as well.

**Comment by eriknelson** [comment]
@jmontleon Maybe we could do a call to compare what @gildub sees as a pipeline compared to the proposed model, and report the conclusion here?

**Comment by jmrodri** [comment]
DirMonitor seems to get a list of files and puts them into a `filesToFetch` channel. The `commBroker` gets a file from the `filesToFetch` pulls said file and puts the contents in the `fetchedFiles` channel. OCP3Decoder pulls file from `fetchedFiles` channel, decodes it and puts the result into `toTranslate` channel. Then OCP4Translator pulls from the `toTranslate` channel, translates the file and writes the result CRD to `manifests` channel.

One thing I see about this pipeline is the channels are all non-buffered channels. This means they have only one item in them and block until the item is read. If we are going to be using channels they should be buffered.

Also, the approach seems to use a "file" as the central object being worked on vs a "component". 

I think I see similarities in the pipeline that @gildub is using and the ETL loop that @eriknelson is proposing. The ETL loop seems to be more defined in that it is an explicit call to discrete actions or steps. It *can* use channels to improve performance but first focus on getting the loop working serially before introducing the concurrent nature of channels.

There doesn't seem to be a way to output multiple translators.  It assumes that a given file has only ONE OCP4 translator:

`file.OCP4.Translate(file.OCP3)`

With the ETL approach there could be a series of Translators that can be in series to create a full translation for an OCP4 component.

Honestly I think any approach that focuses solely on the OCP3 files FIRST will fall short and hit run into problems down the road.

**Comment by gildub** [comment]
@jmontleon, you're right, sorry it's just that it was late for me and I didn't want to block the progress on the ETL approach.

**Comment by gildub** [comment]
The ETL is a good workflow and we can add concurrency to it later proven needed. 
Using the pipeline up front and add the component objects (Oauth, Secrets, SDN, Registries) as the transient interfaces can be done as one concurrency solution.

By pipeline I mean 
`Channels can be used to connect goroutines together so that the output of one is the input to another.` (Definition taken from [1]).

For instance OCP4 components are channels which are passed to ETL operations.
 
[1] "The Go Programming Language" by Brian W. Kernighan; Alan A. A. Donovan. Addison-Wesley Professional, 2015.

**Comment by gildub** [comment]
@jmrodri, somehow I didn't see your post until now.

Thank you for taking the time and reviewing this current approaches and comparing them so we learn more.

The pipeline approach I took was very early, just few weeks ago but feels like ages as I've learned so much since.

**Comment by gildub** [comment]
The ETL is now in place, further adjustment are captured with respective issues.
