### ISSUE TITLE
Proper Error Handling

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#109]
We should probably have better error handling than calling logrus.Fatal and logrus.Panic.

There are times where we're going to have to expect errors and deal with them gracefully. 

One example off the top of my head is looking for files that might not exist. CRI-O was not the default runtime in Openshift 3.x, but it was possible to use. In order to transfer the container runtime configuration we'll need to at least try to fetch the file. If that fails it shouldn't error the program out. Instead we need to simply not create a CR for runtime configuration.

**Comment by alexander-demichev** [comment]
@jmontleon Thanks for bringing it up, I was also thinking about improving error handling. Will take a look at this tomorrow.

**Comment by eriknelson** [comment]
Typically you want to return them with a fn sig that looks like `fn name() (result, error)`, and bubble them up until you hit something that owns the handler.

**Comment by jmrodri** [comment]
In Java, we pretty much bubbled up exceptions all the way to the top. In Go, I tend to try to handle the error at the lowest level if I can, if not, I return it and pass it back to a level that can either handle it or fail.

For example, in the broker we would handle CRD duplicate or missing errors locally in the DAO. In the middle tier if we couldn't handle something we let it go to the handler layer to return an appropriate error message to the user and log a meaningful message to the log.

**Comment by alexander-demichev** [comment]
Can we close it now?

**Comment by eriknelson** [comment]
@alexander-demichev Jason is still seeing examples of us ignoring errors: https://github.com/fusor/cpma/blob/master/pkg/transform/oauth/basicauth.go#L32 #157

**Comment by alexander-demichev** [comment]
@eriknelson Can it be closed now?:) https://github.com/fusor/cpma/pull/163/ fixed it

**Comment by eriknelson** [comment]
I'm sure there are other areas where we miss them, but no need to keep this open. I feel like we established a pattern for how to deal with errors, so let's close this and raise the individual cases if we come across them.
