### ISSUE TITLE
Consider what the translation unit should be called

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#116]
If we believe this problem can be described as a series of `Translations`, where  something asks them to do their ETL work, I think it's important we settle on what we should call this fundamental type that represents the workflow. The names thus far:

* Translator(used today)
* Migration
* Transform
* Operation

We're looking for a name for a type that abstracts the entire workflow of translating a given OCP4 feature, and implements the whole ETL process. Inviting opinion on the existing names, or proposals for new ones.

Issue spawned from a previous PR: https://github.com/fusor/cpma/pull/113#issuecomment-491099484

**Comment by eriknelson** [comment]
I personally like `Migration`. It describes a high level description of what we're doing when we ETL.

**Comment by gildub** [comment]
If the interface name reflects an action/actor, which I believe is the standard practice,
we have Transform/Transformer or Translate/Translator but if we want Migration or Operation then we'd get Migrate/Migrator or Operate/Operator.

**Comment by gildub** [comment]
I believe this has been addressed, please open if needed.
