### ISSUE TITLE
Multiple translations could possibly write to the same output CR

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#117]
Spawned from the discussion on https://github.com/fusor/cpma/pull/113#discussion_r282676836

Quoting from that comment:

> Have we considered the fact that more than one ocp4 feature may need to provide their configuration on the same CR, which means they'd need to edit a shared output file? Perhaps we need to share a data structure between transforms that represents the total file output so that more than one `Translator` can mutate the same individual output file.

**Comment by gildub** [comment]
The model we have in place allows to treat several components "working" on the same CR.
Please create a new issue if needed.
