### ISSUE TITLE
make ci should include lint, gofmt, and govet targets

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#131]
https://github.com/fusor/cpma/blob/master/Makefile#L25

Right now we're just checking the build and test, would be good practice to also enforce lint and gofmt with our CI runs, with the intention that all PRs should pass these before being merged. Devs can confirm their work will pass the checks by just running `make ci` manually.

I don't believe the project is passing lint and/or gofmt currently, so as part of this issue we should repair the breakages.

**Comment by eriknelson** [comment]
@alexander-demichev pointed out we're missing `govet`, which is another good one to include here.

**Comment by alexander-demichev** [comment]
https://github.com/fusor/cpma/pull/153
