### ISSUE TITLE
Consider file retrieval as an independent feature

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#133]
Spawned from PR #128

We have a generic requirement that most (all?) transforms are going to need to get remote file contents as part of their `Extract` methods, to be decoded and stored on an `Extraction` object. It makes sense that we have a dedicated part of the codebase who's only responsibility is to provide this feature. Additionally, we should be able to easily mock it with something that provides `testdata` sourced contents so we can test `Extract` methods well.

If the above is true, we should move `Fetch` [out of transform/transform.go](https://github.com/fusor/cpma/blob/master/pkg/transform/transform.go#L97), and into its own file, and I would advocate a different pkg than `transform`. This is the kind of thing that typically ends up in a `util` package if it's a handful of functions, but if it grows to be more than that, I think it makes sense in its own `file` pkg (name TBD).

It should handle file caching since most transforms will be requesting the same files from it, I know we do that today, but just speccing that here. Additionally, @gildub has pointed out that it's likely that we will need the ability to provide the host as an argument, since it's possible this may need to support a multi-host scenario.

Finally, it could possibly be useful to represent this concept with something like a `FileManager` struct rather than a handful of functions. I don't have a reason for this right now, but I've certainly seen it done for something like this in the past.

At the very least, `Fetch` as it is today should be moved out of that transform file and into something more focused on the concept of file retrieval, and it shouldn't be called from anywhere but transform `Extract` methods, since that's the only place that should be downloading remote files.

Some Q's to be answered:
* Is it possible that in a multi-master scenario, the master config files would differ between masters? If that's not possible, just pick one, and we don't have to care about specifying the host.
* Do we need to get files from nodes as well? If that's true, we know we'll need to at least get files from a master and a node, so that's more than one host, and we'd have to accept the host as an argument here as well. It seems valuable to do this regardless of the answer to the Q's.

**Comment by gildub** [comment]
https://github.com/fusor/cpma/issues/278 is partly replacing this issue as things have evolved.

The Fetch part has already been decoupled from the Transform, and going even furtherto separate remote file fetching as a complete separate pkg, the user being able to fetch files independently.

That said the FileManager idea is still valid and would happen within the latest context.
