### ISSUE TITLE
How should we accept our program arguments?

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#134]
Spawned from https://github.com/fusor/cpma/pull/128#issuecomment-491564445

Reading up some more about cobra, I think I was wrong regarding the above comment, where I stated that we shouldn't have multiple cmd files. It makes sense to me for each command, we should have a different `cmd/X` file (if we have a tool with different commands, ex: `cpma report`, `cpma transform`).

Firstly, do we prefer to accept the output passed as a command vs. an option? Ex:

* Command: `cpma report X`
* Argument: `cpma --output-type={report,transform}`, defaulting to transform?

The first would result in a bunch of `cmd/COMMAND.go` files, and they would also share command line args, like output directory. So does that really make sense over the argument approach?

For maintainability reasons, I like the argument approach. It means we have a single entrypoint. If we think the UX of a command approach is the right choice, then multiple files totally make sense under `cmd/COMMAND.go`.

On top of all this, if we choose to go the command route, what does just `cpma $OPTIONS` do? Just list the help? Default to `transform`?

@jwmatthews curious about your thoughts on this because you stated you liked the command approach. If I had to choose, I like the argument approach because of its maintainability. Admittedly, the command approach is much closer to what `oc` and `kubectl` do today, so I could see that as a point in its favor.

**Comment by jmrodri** [comment]
I think it depends on the number of "commands" you will need and whether they have a complex list of options to override their functionality.

`cpma --output-type=report` is easy enough but if it needs like 5 options to be useful, I'd start looking at making them subcommands instead of options. 

If you only have 2 I'd say options only. If you plan on growing more than 2 or 3 you might want to go the sub command route with their own options. You really need to decide that early because that could totally dictate your direction.

**Comment by gildub** [comment]
I also read afterward @jmontleon pointers to cobra recommendations, so it makes sense.
From that I agree with @jmrodri, too many options would be too heavy in which case the command approach would be better so the question is where do we place the "critical mass" of the number of  options?

**Comment by jwmatthews** [comment]
> Spawned from [#128 (comment)](https://github.com/fusor/cpma/pull/128#issuecomment-491564445)
> 
> Reading up some more about cobra, I think I was wrong regarding the above comment, where I stated that we shouldn't have multiple cmd files. It makes sense to me for each command, we should have a different `cmd/X` file (if we have a tool with different commands, ex: `cpma report`, `cpma transform`).
> 
> Firstly, do we prefer to accept the output passed as a command vs. an option? Ex:
> 
> * Command: `cpma report X`
> * Argument: `cpma --output-type={report,transform}`, defaulting to transform?
> 

I prefer 'cpma report' and 'cpma transform'

-1 on `cpma --output-type={report,transform}`

> The first would result in a bunch of `cmd/COMMAND.go` files, and they would also share command line args, like output directory. So does that really make sense over the argument approach?
> 
> For maintainability reasons, I like the argument approach. It means we have a single entrypoint. If we think the UX of a command approach is the right choice, then multiple files totally make sense under `cmd/COMMAND.go`.
> 
> On top of all this, if we choose to go the command route, what does just `cpma $OPTIONS` do? Just list the help? Default to `transform`?

Default to help

 
> @jwmatthews curious about your thoughts on this because you stated you liked the command approach. If I had to choose, I like the argument approach because of its maintainability. Admittedly, the command approach is much closer to what `oc` and `kubectl` do today, so I could see that as a point in its favor.

**Comment by eriknelson** [comment]
I think we can close this one based on recent progress with `app.Start` and https://github.com/fusor/cpma/issues/114.

The thing I was concerned about was having N different entrypoints that had significant logic in them. I think that is addressed with the push to consolidate the major initial logic to `app.Start`, and to call that from each `cmd/X.go` file. These files should be concerned with dealing with the specifics of that particular command, and handing off those details to `app.Start`.
