### ISSUE TITLE
The new transforms need an example unit test

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#135]
Spawned from https://github.com/fusor/cpma/pull/128#issuecomment-491611443

I provided an example for how to accomplish this here: https://github.com/eriknelson/cpma/commit/bdd651a0616350d178fd39274bd4b80b3abf0424

Specifically this is how I would convert `Flush` into overridable behavior so it becomes testable: https://github.com/eriknelson/cpma/commit/bdd651a0616350d178fd39274bd4b80b3abf0424

I'm not 100% satisfied with pkg level default functions; it doesn't feel like that's a sustainable model for dependency injection (DI). Something to consider, I was chatting with another kubernetes go developer about how people deal with DI in go and there have been some promising proposals in major projects that maybe we could leverage? https://github.com/kubernetes-sigs/controller-runtime/pull/285

Pragmatically I do not think we should adopt this, but it's an interesting option to explore, should we choose to do so.

**Comment by jmontleon** [comment]
https://github.com/fusor/cpma/pull/148
