### ISSUE TITLE
What belongs in the transform/secrets pkg?

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#137]
Spawned from https://github.com/fusor/cpma/pull/128#issuecomment-491528080

@jwmatthews pointed out that there are a set of types that are tightly coupled to `OAuth` that don't feel right to be in a generic secrets package:

https://github.com/fusor/cpma/blob/master/pkg/transform/secrets/secrets.go#L11-L24

This begs the question, should these be part of the `oauth` pkg, and furthermore, what actually belongs in a secrets pkg, and where should it be located?

It makes sense to me that we should have a generic secrets pkg for logic that works with them, but I'm not sure that it belongs under the transform dir. Separately, I think the above types should be in the oauth pkg.

**Comment by gildub** [comment]
This has been covered. Please reopen if needed.
