### ISSUE TITLE
If the target cluster has its config mounted into containers, we can't know the file's true location

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#147]
Wanted to capture this while it's still fresh in my mind in case anyone else runs into this. I'm using https://github.com/fusor/origin3-dev/ for my example ocp3 cluster, which brings up an ec2 vm and runs `oc cluster up` to launch a cluster via docker containers. The cluster's configuration files are stored in a non-default location on the vm, and are mounted into possibly different locations inside the containers.

What this means is that when I run the tool against the cluster, we read the master config and see that htpasswd is configured to be at `/etc/origin/master/htpasswd`. In reality, that file actually exists at `/tmp/openshift.local.clusterup/kube-apiserver/htpasswd` on the vm, but it's mounted into the container at `/etc/origin/master/htpasswd`.

I don't see how we can figure out the true location of the source files if the values in the master config differ from where they actually are on the machine.

@jwmatthews, is this just a product of our particular `origin3-dev` setup, and we're unlikely to encounter this scenario with the production environments we're migrating? Or is this something we need to address?

**Comment by jwmatthews** [comment]
> Wanted to capture this while it's still fresh in my mind in case anyone else runs into this. I'm using https://github.com/fusor/origin3-dev/ for my example ocp3 cluster, which brings up an ec2 vm and runs `oc cluster up` to launch a cluster via docker containers. The cluster's configuration files are stored in a non-default location on the vm, and are mounted into possibly different locations inside the containers.
> 
> What this means is that when I run the tool against the cluster, we read the master config and see that htpasswd is configured to be at `/etc/origin/master/htpasswd`. In reality, that file actually exists at `/tmp/openshift.local.clusterup/kube-apiserver/htpasswd` on the vm, but it's mounted into the container at `/etc/origin/master/htpasswd`.
> 
> I don't see how we can figure out the true location of the source files if the values in the master config differ from where they actually are on the machine.
> 
> @jwmatthews, is this just a product of our particular `origin3-dev` setup, and we're unlikely to encounter this scenario with the production environments we're migrating? Or is this something we need to address?

@eriknelson I will see if I can get a definitive answer.  I assigned this issue to myself and will follow up when I have spoken to some folks on OCP side.

I was thinking perhaps when OCP 3.x clusters were installed from containers and not RPMs maybe there could be a difference in file paths, but unsure.  I've only installed OCP 3.x from rpms.

**Comment by jwmatthews** [comment]
It'd be interesting to see if `oc rsync <pod-name>:/remote/dir/filename ./local/dir` would help.

Perhaps we consider  'oc rsync' opposed to the sftp approach for the referenced files?

This needs more vetting

**Comment by gildub** [comment]
@jwmatthews, @eriknelson, we've seen the limitation of sftp, and rsync would have the same issue if the root user is not allowd through ssh meanwhile we can implement it using ssh commands and sudo.
But the question remains, it this a typical customer use case?

**Comment by alexander-demichev** [comment]
In this case user can fetch files manually and provide them to CPMA. Can we close the issue?

**Comment by gildub** [comment]
Unfortunately the `oc rsync <pod>` approach cannot be used for nodes.
The ssh/sudo approach works for now and otherwise local mode to be used.
Closing it, re-open if needed.
