### ISSUE TITLE
SDN and Oauth Validate functions need to be filled out.

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#150]
Right now these are just spitting warnings. We need to ensure we're getting valid data we can transform here for both.

**Comment by gildub** [comment]
Could we cover cases such as when a field is empty.
For instance with OAuth Keystone is that ok to have a blank ("") value for CA/Cert fields?
I suppose syntactically it's valid but is that logically valid for OCP4?

**Comment by jmontleon** [comment]
Yes, as a very base starting point I think we would want to verify we got one or more providers back.

And then it's probably worth making sure every one (at least every type we support) we get back has valid content for us to put together a valid CR.

I'll again defer to @eriknelson but I think I could see having a validate function we call out to from Validate for each type of provider since the logic could get a little crazy otherwise.

**Comment by alexander-demichev** [comment]
I am starting to work on oAuth validation

**Comment by alexander-demichev** [comment]
https://github.com/fusor/cpma/pull/174
