### ISSUE TITLE
Factorize Master, Node, configuration file unmarshalling.

### ISSUE THREAD

**Issue by gildub** [fusor/cpma#154]
I thought someone mentioned it but I cannot find in PR#128 a comment about it.

Anyway, since lots of components are sub set of the same configuration file, shouldn't we rely on a helper to handle each time we tap into a MasterConfig, or NodeConfig, etc.

For instance, these 2 blocks have the same use and both share configV1.MasterConfig: 
https://github.com/fusor/cpma/blob/master/pkg/transform/oauth_transform.go#L57-L66
https://github.com/fusor/cpma/blob/master/pkg/transform/sdn_transform.go#L103-L110

Helpers could be something like:
https://github.com/fusor/cpma/blob/8c7523c9ec9a90959fae074a9ab02b6533f7f835/pkg/ocp3/ocp3.go#L24-L49
 
Your thoughts?

**Comment by jmontleon** [comment]
I think the more we can cut down on duplicate code the better. 

As to where it would live, maybe we could get all our decoders for various formats in pkg/util/decode.go or something. I'll defer to @eriknelson as to where might be best.

Even better if we can make it more generic to handle any json content. Likewise, TOML, YAML, INI, and anything else we're going to have to deal with. All the better if we can use it to eliminate all the places I copy/pasted it into tests too. Was just commenting to the same effect on @alexander-demichev's error handling PR as well.

**Comment by eriknelson** [comment]
> Anyway, since lots of components are sub set of the same configuration file, shouldn't we rely on a helper to handle each time we tap into a MasterConfig, or NodeConfig, etc.

> I think the more we can cut down on duplicate code the better.

Absolutely. I could almost picture a `config` pkg with all the data structures that you would decode into, as well as the decoder logic (that could even be in a `decode` pkg found at `config/decode/`). Some pseudocode usage of this would look something like:

**oauth_transform.go**
```
import (
  "github.com/fusor/cpma/pkg/config"
  "github.com/fusor/cpma/pkg/config/decode"
  ...
)

func Extract() {
    var masterConfig config.MasterConfig
    decode.MasterConfigDecode(masterConfig, GetFile(env.Config.MasterConfigFile))
    // Build an Extraction based on the data we've now got in the masterConfig
}
```
