### ISSUE TITLE
secretType with GenSecret and the switch in buildData should be an enum

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#158]
https://github.com/fusor/cpma/blob/master/pkg/transform/secrets/secrets.go#L68

It's preferable to use an enum to represent something like this so it uses a strong type and won't accept a `secretType` that isn't part of the possible set (the compiler will stop it in its tracks).

Go doesn't have enums, but there are idiomatic ways they can be approximated:

```
type Direction int

const (
    North Direction = iota
    East
    South
    West
)

func (d Direction) String() string {
    return [...]string{"North", "East", "South", "West"}[d]
}
```

https://yourbasic.org/golang/iota/

**Comment by alexander-demichev** [comment]
@Danil-Grigorev volunteered to help with this issue
