### ISSUE TITLE
Make GenYaml common function

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/cpma#167]
`GenYAML()` is repeated twice for secrets and ouath - https://github.com/fusor/cpma/blob/1aa6ac9fc61860ec87f9326cd38f339dcc748b56/pkg/transform/secrets/secrets.go#L88 https://github.com/fusor/cpma/blob/55ef73f43a10785b6a76bd3a2e07a428d25603a0/pkg/transform/oauth/oauth.go#L159

Maybe we need to make it common for both of them and later we will need `GenYAML()` for more CRs.

**Comment by gildub** [comment]
Secrets are used by OAuth but they are might be used by other components. 
I think we should handle them on their own.
In such case we might actually want to retrieve the secrets before handling any other components.

**Comment by gildub** [comment]
To share GenYAML is likely to involve interface{} to have a generic function, which means to switch over the possible objects passed as interfaces. 

I think it's better to have a small function for each component instead of a big GenYAML treating all the case. But that's only my viewpoint.
