### ISSUE TITLE
cpma.log.json is not a valid json

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/cpma#196]
Example:
```
{
  "level": "error",
  "msg": "Unable to read private key: ",
  "time": "2019-06-06T16:31:59+02:00"
}
{
  "level": "error",
  "msg": "Unable to read private key: ",
  "time": "2019-06-06T16:31:59+02:00"
}
{
  "level": "error",
  "msg": "Unable to read private key: ",
  "time": "2019-06-06T16:31:59+02:00"
}
{
  "level": "error",
  "msg": "Unable to read private key: ",
  "time": "2019-06-06T16:31:59+02:00"
}
```

We need to wrap these objects with array `[{...},{...}]` or change format of this file

**Comment by arapov** [comment]
Should we care about this? Although, when/if someone decide to fix it, please also pay attention to the fact that we may want to send json log messages to some recipient, such as UI.

**Comment by jmontleon** [comment]
From what I saw reading through some logrus docs is that the messages were put in JSON format to make log parsing by splunk, etc. easier. I don't know that the intention was ever to make the entire log proper json

**Comment by arapov** [comment]
Yeah, exactly.
