### ISSUE TITLE
OAuth: Add missing and report unsupported parameters 

### ISSUE THREAD

**Issue by gildub** [fusor/cpma#197]
Add the following parameters which are supported in OCP4 OAuth CRD spec:
- template -> error -> name
- template -> login -> name
- template -> providerSelection -> name
- tokenConfig -> accessTokenMaxAgeSeconds

Mark as unsupported, only if value is set:
- AlwaysShowProviderSelection
- AssetPublicURL
- MasterCA
- MasterPublicURl
- MasterURL
- SessionConfig:
  - sessionMaxAgeSeconds
  - sessionName
  - sessionSecretsFile
- tokenConfig -> authorizeTokenMaxAgeSeconds

**Comment by jmontleon** [comment]
I think tokenConfig -> accessTokenMaxAgeSeconds was one of the items we were asked for. Would be great if we can do this.

**Comment by alexander-demichev** [comment]
I will work on this
