### ISSUE TITLE
Network: Add supported parameters and report unsupported ones

### ISSUE THREAD

**Issue by gildub** [fusor/cpma#199]
Add supported OCP3 master-config's network parameters:
- `ingressIPNetworkCIDR`: https://docs.openshift.com/container-platform/4.1/networking/ingress-operator.html#configuring-ingress.

Report unsupported parameters:
- `externalIPNetworkCIDRs`
- `HostSubnetLength`

**Comment by alexander-demichev** [comment]
Thanks for tracking it!
