### ISSUE TITLE
'Survey' - error on empty value

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/cpma#216]
CPMA should fail if one of values prompted by `survey` was left empty, in the same way it is done in openshift-installer.

**Comment by arapov** [comment]
I didn't try openshift-installer for empty values... May be it's better not to fail, rather keep asking, require input?

**Comment by alexander-demichev** [comment]
You are right, `survey` has validation support, we can ask again on empty value. We also need to make CPMA react on interrupt signal, currently on `ctrl+d` it just switches to next value.
