### ISSUE TITLE
Document supported use cases and workflows to execute.

### ISSUE THREAD

**Issue by jwmatthews** [fusor/cpma#242]
This issue is to track work to create a 'scenarios' folder similar to https://github.com/fusor/mig-controller/tree/master/docs/scenarios

The purpose of 'docs/scenarios' for CPMA is to create documentation on the high level use cases we will support along with any sample data needed to recreate those scenarios.

For example, this may include sample yamls or master-config.yaml snippets which have certain configurations to apply in OCP 3 so we may exercise CPMA tool and produce desired Reports/CRs to apply to OCP 4.x.

These engineering docs will help the community to understand the capabilities of the tool and serve as on-boarding, as well as help QE and Docs.

**Comment by alexander-demichev** [comment]
https://github.com/fusor/cpma/pull/309/

**Comment by alexander-demichev** [comment]
https://github.com/fusor/cpma/issues/336
