### ISSUE TITLE
Testing / Early Access Preparation

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#258]
Test and ensure that our reporting and transforms work against:
- [x] 3.7
- [x] 3.9
- [x] 3.10
- [x] 3.11

Ensure that transforms generated from each applies to Openshift 4.x
- [x] 3.7
- [x] 3.9
- [x] 3.10
- [x] 3.11

**Comment by Danil-Grigorev** [comment]
Transform testing is introduced in https://github.com/fusor/mig-ci/pull/68. Report generation is a partially implemented in https://github.com/fusor/cpma/pull/285 , the issues with current solution are documented in https://github.com/fusor/cpma/issues/300
