### ISSUE TITLE
Prompts for settings do not respond properly to interrupt (ctrl+c)

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#259]
If you start CPMA and start getting prompted for settings and hit ctrl+c, instead of exiting, survey instead proceeds to the next question. This may be a limitation of the survey library and I'm not sure we can fix it without work on the library or looking for a different alternative.

**Comment by arapov** [comment]
Yes, we've seen and discussed with @alexander-demichev  this behavior. It doesn't handle ^D as well. The library itself must be fixed. openshift installer, and other apps that uses survey library suffer from it.

This may be a stretch goal for Sprint 8. The fix should be pushed to survey lib upstream, which we have no guarantee we get handled by the end of the Sprint 8.

**Comment by arapov** [comment]
Doh... Folks, a little bit of googling and https://github.com/AlecAivazis/survey/issues/117#issuecomment-360380938

We just have to check the survey.AskOne() for err.Error() == "interrupt"

so taking my words about stretch goal back. :)

**Comment by jmontleon** [comment]
If it's quick that works even better. I put it on the backlog. I think features will be a priority for Sprint 8, so agree if it's going to take a lot of work we can hold off.
