### ISSUE TITLE
No indication of error when a host is unreachable.

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/cpma#270]
During an execution on a destroyed cluster, none of the existing output options displayed an error on an unexciting cluster address. The output contained only warnings:
```
WARN[30 Jun 19 17:12 CEST]/home/dgrigore/Documents/work/openshift/cpma/pkg/transform/transform.go:139 github.com/fusor/cpma/pkg/transform.HandleError() Skipping ClusterReport - Get https://35.157.81.28.xip.io:8443/api/v1/namespaces: dial tcp 35.157.81.28:8443: i/o timeout
```

**Comment by gildub** [comment]
@Danil-Grigorev, would you expect the warning to be changed into an error?

**Comment by alexander-demichev** [comment]
My suggestion is to add warning log level here https://github.com/fusor/cpma/blob/master/pkg/env/env.go#L454
