### ISSUE TITLE
Lack of unit testing for modules.

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/cpma#271]
Most of the existing tests are targeting general functionality of a tool, but not the error handling or edge cases of usage.

Example:
This [function](https://github.com/fusor/cpma/blob/acb95c7539c1768be12bb5171e45cdeb0edb1c2a/pkg/transform/cluster_report_transform.go#L170) is used only in error messages, but none of the tests cover its execution.

We need to extend the existing tests with unit tests to improve code coverage.

**Comment by alexander-demichev** [comment]
Amount of unit tests looks fine now, most important logic is covered. Closing this.
