### ISSUE TITLE
Make k8s and o7t API client creation failure a failure (or not)?

### ISSUE THREAD

**Issue by gildub** [fusor/cpma#272]
Failure to add either API clients will raise an error and propagate.
It might make more sense to make it a fatal error and stop CPMA as the report system rely on them.

**Comment by Danil-Grigorev** [comment]
I would agree that usage of panic is a better solution in case of `once.Do`. We won't loose the error message and the code simplification is in place.
```
	once.Openshift.Do(func() {
		client, err := newOpenshift(config)
		if err != nil {
			log.Panic(err)
		}
		instances.Openshift = client
	})
	return instances.Openshift, nil
```
There is a benefit in inclusion of `log` package in the api. We will have all dependencies in place, and may use the logrus from there too.

**Comment by alexander-demichev** [comment]
I think now CPMA started to become more analytics than translation tool and API clients are crucial here. Let's `panic` in case of error and rename function to `newOpenshiftOrDie()`, this way it will be more obvious, for someone new, that creating API can panic.

**Comment by Danil-Grigorev** [comment]
It is also a common practice in Golang, I agree with this suggestion to use `panic` in such case.
