### ISSUE TITLE
Consider alternative for retreiving node hostnames from k8s api.

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/cpma#274]
Related to #252 

Most of the sample multinode deployments which are close to a customer-like state are using internal hostnames for communication between nodes. Here is the survey of nodes from agnosticd:
```
? Select master node  [Use arrows to move, space to select, type to filter]
  infranode1.ci-agnosticd-p-101.internal
> master1.ci-agnosticd-p-101.internal
  node1.ci-agnosticd-p-101.internal
```
This is how the k8s api sees it. This leads to a following error:
```
WARN[01 Jul 19 15:33 CEST]/home/dgrigore/Documents/work/openshift/cpma-my/pkg/transform/transform.go:139 github.com/fusor/cpma/pkg/transform.HandleError() Skipping API - Cannot connect to master.ci-agnosticd-p-101.internal:22
: dial tcp: lookup master.ci-agnosticd-p-101.internal on 10.34.129.60:53: no such host 
```
This issue can easily be fixed by specifying the external hostname, which is ` master1.ci-agnosticd-p-101.mg.dog8code.com`

So the following fixes could be applied:
1) Add an option to get master node address from user input. (This is how it is fixed now, by substitution of `.internal` prefix to `.mg.dog8code.com`)
2) Find a resource in openshift, which specifies the information we need, and then get the value from API.
3) Preprovision clusters with external hostnames for nodes (as it is done in quicklab based deployment), and document this step in prerequisites to CPMA.

What is a better solution?

**Comment by jwmatthews** [comment]
I would view a cluster as having 2 main external interfaces:
 - API endpoint
 - Routes endpoint

Other than those 2 endpoints, I don't think we can rely on further external access....assume it will be a case that some configurations may expose more, some less.  

Not being able to ssh into masters or nodes will likely be a valid deployment.  Think we will need a flexible approach, where if it's not possible to ssh in a node we need to provide an alternative method of making the needed configuration present, perhaps a fallback of inform end user they need to obtain the needed node configuration files if they want them processed.

Thinking the fallback approach could be:
 - Rely on user to obtain the needed files (we display via CPMA output the specific files we want fetched)
 - User stores the files in a directory and then re-runs cpma specifying the dir containing the files.

**Comment by alexander-demichev** [comment]
@jwmatthews Hi John, reading config yamls locally instead of using ssh makes sense. We already have some caching implemented, CPMA reuses fetched files. This behavior can be extended by asking user for source of config files using `survey`.

**Comment by gildub** [comment]
@jwmatthews, we're already fetching the files if they are available. 
This is documented in Readme, the only case we need to cover is if the path is different then defaults and that's also cover with default values, just need to included into Survey, as @alexander-demichev mentioned.

**Comment by gildub** [comment]
This has been covered. Please reopen if needed.
