### ISSUE TITLE
Report e2e testing.

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/cpma#300]
The PR #285 introduced e2e test for report generation. The test compares generated report with expected, but it is very reliant on a specific stable cluster. There is no way to freeze the cluster, so for example the report could change when a new namespace resource was created (openshift-logging do this all the time, as it is monitoring the cluster).

Things needs to be fixed.

- [ ] Create specific means for updating source reports for comparison (Example: Some daily build will update the report). Such update could be triggered at any moment manually.
- [ ] Disconnect the test from specific cluster, and make the source vary.
- [ ] Create a human readable test output, which will show the difference between tested reports.

**Comment by gildub** [comment]
Just to clarify when we get back to this.

The reports have 2 different kind of sources, one is based upon configuration parameters where we track parameters that are fully or partially supported or not at all, and the second source is from querying cluster's APIs to report about resources content (pods, hosts, etc). 

For the first part we try to be as exhaustive as possible and cover control plane parameters, the presence of such parameter can be sometime optional but if present we provide report about it.

For the second part we report what we find in the cluster, which can varies depending on each case.

For the tests, we try to have data sets as exhaustive as possible.
Which implies covering all control panel parameters and all different type of resources.
As we generate the reports we need to cover the functions involved with unit tests.
But I don't see what would bring end to end test to the data sets.

**Comment by gildub** [comment]
@Danil-Grigorev, per our off line discussion I close it. If needed please reopen.
