### ISSUE TITLE
Use ssh instead of sftp to be able to use sudo commands

### ISSUE THREAD

**Issue by gildub** [fusor/cpma#31]
Although it might sound more natural to use sftp to retrieve the nodes' configuration files, ssh is more flexible to handle advanced admin operations.
The use case is more specifically when nodes are configured with an dedicated user which has sudo privileges and the admin(root) user is not allowed for ssh/sftp.

**Comment by arapov** [comment]
I guess we'll need some input from field, confirming this is something expected that we can't login as root/someone who has an access to /etc/origin.

**Comment by arapov** [comment]
I was thinking about this a little again. I don't like this idea, even if we implement this - we create security risk. I am sure, providing users with sftp is already enough and risky. I envision smarter users/admins must prefer local copy of openshift cluster configuration. And CPMA tool must be capable to guide the configuration conversion and suggest where to get missing configuration data when not available.

IOW, it is another clear NAK from me for this feature.
@gildub, @alexander-demichev, any concerns before I close it?

**Comment by gildub** [comment]
@arapov, I don't see the difference risk between providing a user which has sudo access versus a root admin user. In both cases we're relying on ssh security layer of the user to run the tool from a host where the ssh keys are present and the host in question to be on the authorized hosts list.

Of course with files being transferred locally before lower security risks but that doesn't solve the need for when the tool needs to access the cluster and the endpoint is the option selected by the admin user. 

I believe we have to address this.

**Comment by gildub** [comment]
The current work is to allows files to be copied prior top tool exec.
Then the tool uses those local files.

**Comment by gildub** [comment]
PR#105 addresses the issue. 
Feel free to re-open if needed.

**Comment by gildub** [comment]
Reopened as the case appeared with agnosticd CI but is potentially facing any customer.

Currently CPMA can't get the files accessible only by admin user (root).
Effectively the golang sftp package doesn't offer the option to sudo on the sftp server as opposed to full feature sftp client (CLI for instance).

There are a couple of work around to retrieve the files when a deployment environment only allows access to root hrough `sudo` (and therefore won't allow to change sshd rules).
- Using ssh and add sudo command
- `sftp -i ~/.ssh/my-key -s "sudo /usr/libexec/openssh/sftp-server" ec2-user@openshift-master.example.com:/etc/origin/master/master-config.yaml`

For offering the feature to CPMA we could;
- Use golang ssh client with sudo command
- Spawn a command to system to run `sftp -s "sudo  /usr/libexec/openssh/sftp-server" as above

**Comment by Danil-Grigorev** [comment]
The behavior in https://github.com/fusor/cpma/issues/31#issuecomment-507278419 seems more valid to me. The default `ec2-user` user has `no-passwd` access to the sudo, so the line provided there will not cause any issues, and will decrease the amount of prerequisites needed for CPMA. Also, in case we will figure out some other issues, `ssh` access will grantee the ability to fix them automatically. But it is better to use the golang library.
