### ISSUE TITLE
Add a capability to report to highlight usage of SCCs in namespaces and highlight usage.

### ISSUE THREAD

**Issue by jwmatthews** [fusor/cpma#337]
Would like to see cpma able to solve the problem of how can a user know that a namespace they plan to migrate depends on a custom SCC.

Thinking 2 pieces of information would help to solve this:
 - When viewing the SCCs available, add a field that tracks what namespaces they are used in

```
Something like
{
          "name": "fooSCCName",
          "users": [],
          "groups": [
            "system:cluster-admins"
          ],
          "namespaces": [ "foo-test-ns-1", "foo-test-ns-2"]
},
```

- When viewing a namespace, having the info captured here would help as well
```
Perhaps we just capture the name when under the namespace report
"securityContextConstraints": ["restricted", "fooSCCName"]
```

**Comment by alexander-demichev** [comment]
SCCs are cluster scoped objects and the only available spec that can tell if SCC is used by a namespace is user list:
```
Name:	privileged
Priority:	<none>
Access:
  Users:	system:admin,system:serviceaccount:openshift-infra:build-controller,system:serviceaccount:velero:velero,system:serviceaccount:default:build-robot
  Groups:	system:cluster-admins,system:nodes,system:masters
```
My suggestion is to look if user list contains service account, then look to which namespace SA belongs and build dependency between namespace and SCC based on SA.
