### ISSUE TITLE
While CPMA is working print some status to console

### ISSUE THREAD

**Issue by alexander-demichev** [fusor/cpma#350]
Currently if CPMA is running without `--verbose`  or `--debug` there is no info about report/transform status unless something fails. Will be nice to print at least something like `Transform/report started`, `Transform/report succeeded` etc.

**Comment by gildub** [comment]
Well initially that was the idea, but all output went under `--verbose` (and as well as under `--debug` put that's a different purpose). 

I think we're misleading the purpose of the verbose option, we should rename it `--silent` and then add in `--verbose` detailed messages that could be useful in cases.

**Comment by alexander-demichev** [comment]
Let's rethink what is printed to terminal. Biggest part of logs should go to debug level and be shown using `--debug`, remaining logs should go to info level and be shown shown to user unless `--silent` command is used.

**Comment by gildub** [comment]
Yes, so let's remove `--verbose` and replace it with `--silent` by reversing current behavior so nothing is displayed if used. Of course this shouldn't impact the logs.

**Comment by alexander-demichev** [comment]
https://github.com/fusor/cpma/pull/375
