### ISSUE TITLE
Add ability to configure alternate configuration locations on OCP3 cluster

### ISSUE THREAD

**Issue by dymurray** [fusor/cpma#76]
Currently this tool does not work with any `oc cluster up` environments. That isn't a huge deal since we don't support `oc cluster up` but for development it would be nice to test this against dev environments that use `oc cluster up`. 

Would be nice if https://github.com/fusor/cpma/blob/master/ocp3/ocp3.go#L104 was configurable in my `.cpma.yaml` file.

**Comment by arapov** [comment]
We didn't pay much attention to oc cluster up. We will look into it.

@dymurray do you think the location of master and node config files can be different? Why would you want to change it?

**Comment by dymurray** [comment]
Yeah I know they can be different :) When you run `oc cluster up` it creates a directory `openshfit.local.clusterup` which has `openshift-apiserver/master-config.yaml` and `node/node-config.yaml`. 

I hardcoded these paths in my fork:
```
// New instantiates and returns Config structure that represents OCP3 configuration
func New() *Config {
        return &Config{
                Masterf: "/tmp/openshift.local.clusterup/openshift-apiserver/master-config.yaml",
                Nodef:   "/tmp/openshift.local.clusterup/node/node-config.yaml",
        }
}
```

I think it makes sense to focus on `/etc/origin` since that is where production installs places these files. This is more just a nice to have thing for development.
