### ISSUE TITLE
Remove event loop in `cmd/root.go`

### ISSUE THREAD

**Issue by dymurray** [fusor/cpma#78]
I am having trouble seeing any reason why we need a timeout based event loop here: https://github.com/fusor/cpma/blob/master/cmd/root.go#L58.

When the results are successful, the `cpma` tool runs for 10 seconds repeating the same behavior over and over again until it times out. I can't think of any good reason why we would need this loop. Am I missing something here?

**Comment by arapov** [comment]
ACK

**Comment by arapov** [comment]
@gildub, I do agree with folks that we don't need this optimization, at least at this stage of the project. Let's just forget about it for the time being and get back once we do feel we miss it.

**Comment by gildub** [comment]
The idea behind was to monitor activity on the file system and trigger a new sequence of fetch,decode, translate. No worries, let's get rid of it.
