### ISSUE TITLE
README needs developer getting started instructions

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#84]
I checked out the project to my `GOPATH` and using go 1.12.4, it will not build using `make`. Cloning to a location outside of my `GOPATH` does work. I understand there's some weirdness around go modules and go binary versions, so we should clearly communicate expectations in the README:

* What go versions are supported?
* Where the project should be checked out to?
* Any special requirements like setting `GO111MODULE="on"`?

**Comment by alexander-demichev** [comment]
Thanks for catching it, I will add more dev setup info to readme tomorrow.

**Comment by alexander-demichev** [comment]
https://github.com/fusor/cpma/pull/94

**Comment by alexander-demichev** [comment]
@eriknelson Take a look at https://github.com/fusor/cpma/pull/94 and let me know if there is anything else, that need to be added.

**Comment by eriknelson** [comment]
This was filed prior to Jason fixing the build by committing the go mod flag to the default target, so I think we're good on this, thanks
