### ISSUE TITLE
Need to be able to handle non-json configuration files

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#90]
ETCD configuration is in /etc/etcd/etcd.conf
CRI-O runtime configuration is in /etc/crio/crio.conf

Both are ini files and trying to adding them to the download/transform causes an error trying to unmarshal json.

**Comment by alexander-demichev** [comment]
I think work on fetching something besides master/node is still in progress.
@gildub should know more.

**Comment by gildub** [comment]
If ETCD and CRI-O are within scope (to be confirmed), then need to add INI format.

**Comment by jmontleon** [comment]
https://github.com/fusor/cpma/pull/108/commits demonstrates it is possible to handle different file formats.
